In [20]:
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler

In [3]:
df=load_breast_cancer()

In [4]:
x=pd.DataFrame(data=df.data,columns=df.feature_names)

In [5]:
x

     mean radius  mean texture  mean perimeter  ...  worst concave points  worst symmetry  worst fractal dimension
0          17.99         10.38          122.80  ...                0.2654          0.4601                  0.11890
1          20.57         17.77          132.90  ...                0.1860          0.2750                  0.08902
2          19.69         21.25          130.00  ...                0.2430          0.3613                  0.08758
3          11.42         20.38           77.58  ...                0.2575          0.6638                  0.17300
4          20.29         14.34          135.10  ...                0.1625          0.2364                  0.07678
..           ...           ...             ...  ...                   ...             ...                      ...
564        21.56         22.39          142.00  ...                0.2216          0.2060                  0.07115
565        20.13         28.25          131.20  ...                0.1628          0.2572                  0.06637
566        16.60         28.08          108.30  ...                0.1418          0.2218                  0.07820
567        20.60         29.33          140.10  ...                0.2650          0.4087                  0.12400
568         7.76         24.54           47.92  ...                0.0000          0.2871                  0.07039

[569 rows x 30 columns]

In [10]:
y=pd.DataFrame(df["target"])

In [11]:
y

     0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.80,random_state=10)

In [13]:
model=DecisionTreeClassifier()

In [14]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [15]:
y_pred=model.predict(x_train)

In [16]:
accuracy_score(y_train,y_pred)

1.0

In [18]:
y_test_predict=model.predict(x_test)

In [19]:
accuracy_score(y_test,y_test_predict)

1.0

In [21]:
min_max_scaler=MinMaxScaler()

In [22]:
scaler=min_max_scaler.fit_transform(x)

In [23]:
scaler

array([[0.52103744, 0.0226581 , 0.54598853, ..., 0.91202749, 0.59846245,
        0.41886396],
       [0.64314449, 0.27257355, 0.61578329, ..., 0.63917526, 0.23358959,
        0.22287813],
       [0.60149557, 0.3902604 , 0.59574321, ..., 0.83505155, 0.40370589,
        0.21343303],
       ...,
       [0.45525108, 0.62123774, 0.44578813, ..., 0.48728522, 0.12872068,
        0.1519087 ],
       [0.64456434, 0.66351031, 0.66553797, ..., 0.91065292, 0.49714173,
        0.45231536],
       [0.03686876, 0.50152181, 0.02853984, ..., 0.        , 0.25744136,
        0.10068215]], shape=(569, 30))

In [24]:
scaler_df=pd.DataFrame(data=scaler,columns=df.feature_names)

In [25]:
scaler_df

     mean radius  mean texture  mean perimeter  ...  worst concave points  worst symmetry  worst fractal dimension
0       0.521037      0.022658        0.545989  ...              0.912027        0.598462                 0.418864
1       0.643144      0.272574        0.615783  ...              0.639175        0.233590                 0.222878
2       0.601496      0.390260        0.595743  ...              0.835052        0.403706                 0.213433
3       0.210090      0.360839        0.233501  ...              0.884880        1.000000                 0.773711
4       0.629893      0.156578        0.630986  ...              0.558419        0.157500                 0.142595
..           ...           ...             ...  ...                   ...             ...                      ...
564     0.690000      0.428813        0.678668  ...              0.761512        0.097575                 0.105667
565     0.622320      0.626987        0.604036  ...              0.559450        0.198502                 0.074315
566     0.455251      0.621238        0.445788  ...              0.487285        0.128721                 0.151909
567     0.644564      0.663510        0.665538  ...              0.910653        0.497142                 0.452315
568     0.036869      0.501522        0.028540  ...              0.000000        0.257441                 0.100682

[569 rows x 30 columns]

In [26]:
pca=PCA(n_components=3)

In [27]:
x_pca=pca.fit_transform(scaler_df)

In [29]:
x_pca=pd.DataFrame(data=x_pca)

In [30]:
x_pca

            0         1         2
0    1.387021  0.426895 -0.541703
1    0.462308 -0.556947 -0.205175
2    0.954621 -0.109701 -0.147848
3    1.000816  1.525089 -0.053271
4    0.626828 -0.302471 -0.409336
..        ...       ...       ...
564  1.002840 -0.474785 -0.100041
565  0.620757 -0.517200  0.400360
566  0.226311 -0.287946  0.315224
567  1.677834  0.335946  0.296116
568 -0.905068 -0.104109  0.382860

[569 rows x 3 columns]

In [32]:
x_train,x_test,y_train,y_test=train_test_split(x_pca,y,train_size=0.80,random_state=10)
model=DecisionTreeClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_train)
print(accuracy_score(y_train,y_pred))
y_test_predict=model.predict(x_test)
print(accuracy_score(y_test,y_test_predict))

1.0
0.9385964912280702